OTWO-6778 project_id missing in github mass import
blackducksoftware/ohloh-ui pull request #1647
Opened 2022-08-18 08:55 UTC by Niharika1117

2022-08-18 09:23 UTC, Niharika1117 commented
retest this please

2022-08-18 10:03 UTC, notalex requested changes

2022-08-18 10:03 UTC, notalex commented on app/models/github_user.rb
> +      CodeLocationSubscription.create(params) if code_location
Is there a scenario where `@code_locations` has `nil` values?

2022-08-22 11:38 UTC, Niharika1117 commented
retest this please

2022-08-22 17:05 UTC, notalex approved these changes

2022-08-23 08:55 UTC, merged