OTWO-6875 Sql injection Fix
blackducksoftware/ohloh-ui pull request #1681
Opened 2022-11-23 16:29 UTC by Niharika1117

2022-11-24 08:38 UTC, Priya5 approved these changes

2022-11-30 13:06 UTC, notalex commented on app/controllers/api/v1/enlistment_controller.rb
> +                                  #{ActiveRecord::Base.sanitize_sql(code_location_id)};")
This `code_location_id` comes directly from the DB. We shouldn't need to sanitize it here. You may undo this change.
Is there any way to mark this line as safe for coverity scan?

2022-11-30 13:08 UTC, notalex commented on app/controllers/edits_controller.rb
> +                                                                @parent.id]))
This change is also not required.

2022-11-30 13:24 UTC, notalex requested changes
Please review all the changes here and only sanitize values that come directly from end users.

2022-12-08 11:25 UTC, closed without merging